"""BeamGenius — Deterministic reinforced-concrete beam engineering core (Phase 1)."""

from beamgenius.domain import (
    BeamComplianceReport,
    BeamGeometry,
    CalculationTraceStep,
    ConcreteMaterial,
    DiagnosticSeverity,
    EffectiveDepthResolution,
    EngineeringDiagnostic,
    EvaluationOutcome,
    FlangeCondition,
    JurisdictionMode,
    OverallComplianceStatus,
    RebarGroup,
    RebarMaterial,
    RuleCategory,
    RuleReference,
    SectionType,
    StirrupLayout,
    VerificationStatus,
)
from beamgenius.engine import (
    DEFAULT_MABHAS9_CHECK_RULES,
    aggregate_compliance_report,
    evaluate_mabhas9_effective_flange_width,
    evaluate_mabhas9_flexural_capacity,
    evaluate_mabhas9_phi_factor,
    evaluate_mabhas9_strain_and_ductility_limit,
    evaluate_mabhas9_stress_block_parameters,
    evaluate_maximum_stirrup_spacing,
    evaluate_minimum_flexural_reinforcement,
    evaluate_minimum_shear_reinforcement,
    run_mabhas9_beam_check,
    run_mabhas9_flexural_workflow,
)
from beamgenius.registry import (
    RULE_REGISTRY,
    evaluate_rule_gate,
    get_rule,
    list_all_rules,
    list_blocked_rules,
    list_mabhas9_executable_rules,
    list_reference_executable_rules,
    require_rule,
)

__version__ = "0.1.0"

__all__ = [
    "BeamComplianceReport",
    "BeamGeometry",
    "CalculationTraceStep",
    "ConcreteMaterial",
    "DEFAULT_MABHAS9_CHECK_RULES",
    "DiagnosticSeverity",
    "EffectiveDepthResolution",
    "EngineeringDiagnostic",
    "EvaluationOutcome",
    "FlangeCondition",
    "JurisdictionMode",
    "OverallComplianceStatus",
    "RULE_REGISTRY",
    "RebarGroup",
    "RebarMaterial",
    "RuleCategory",
    "RuleReference",
    "SectionType",
    "StirrupLayout",
    "VerificationStatus",
    "__version__",
    "aggregate_compliance_report",
    "evaluate_mabhas9_effective_flange_width",
    "evaluate_mabhas9_flexural_capacity",
    "evaluate_mabhas9_phi_factor",
    "evaluate_mabhas9_strain_and_ductility_limit",
    "evaluate_mabhas9_stress_block_parameters",
    "evaluate_maximum_stirrup_spacing",
    "evaluate_minimum_flexural_reinforcement",
    "evaluate_minimum_shear_reinforcement",
    "evaluate_rule_gate",
    "get_rule",
    "list_all_rules",
    "list_blocked_rules",
    "list_mabhas9_executable_rules",
    "list_reference_executable_rules",
    "require_rule",
    "run_mabhas9_beam_check",
    "run_mabhas9_flexural_workflow",
]
